name: hello world
run-name: hello ${{ inputs.name }} run

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the user triggering workflow
        required: true
        type: string
      last_name:
        description: Last name of the user triggering the workflow
        required: true
        type: string
jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: |
          echo "Hello there ${{ inputs.name }}"
  print_last_name:
    runs-on: ubuntu-latest
    outputs:
      characters_length: ${{ steps.characters_length.outputs.length }}
    steps:
      - name: Print last name
        run: |
          echo "My last name is ${{ inputs.last_name }}"
      - name: Count characters
        id: characters_length
        run: |
          last_name="${{ inputs.last_name }}"
          length=${#last_name}
          echo "length=$length" >> $GITHUB_OUTPUT
      - name: Test
        run: |
          echo "Length inside previous step: ${{ steps.characters_length.outputs.length }}"
  summary:
    runs-on: ubuntu-latest
    needs: print_last_name
    steps:
      - name: Display summary
        run: |
          echo "### Summary - Length of last name: ${{ needs.print_last_name.characters_length }}" >> $GITHUB_STEP_SUMMARY
        
